### ISSUE TITLE
[Admin] TaskAssessments

### ISSUE THREAD

**Issue by sveredyuk** [DevChallengeIT/devchallenge-platform#10]
- As an admin, I want to CRUD task assessment
- Repo::TaskAssessment model:

```
Table task_assessments {
  id id
  value integer
  comment text
  member_id id [ref:> members.id]
  task_criteria_id id [ref: > task_criterias.id]
  task_submissions_id id [ref: > task_submissions.id]
}
```
```
class Repo::TaskAssessment 
  belongs_to :member
  belongs_to :task_submission
  belongs_to :task, through: :task_submission
  
  has_one :task_criteria
  ...
end
```

- route /admin/tasks/:id/assessments

**Comment by PyrinAndrii** [comment]
@sveredyuk, please review the issue description, and correct if I understood it wrong or missed anything.

**Comment by sveredyuk** [comment]
Everything is fine, but let's change one small thing:
`belongs_to :member` instead of the user. Let's keep everything related to the challenge inside challenge data

**Comment by PyrinAndrii** [comment]
> Everything is fine, but let's change one small thing: `belongs_to :member` instead of the user. Let's keep everything related to the challenge inside challenge data

sure, changed it, I thought the same thing.
I will work on it

**Comment by sveredyuk** [comment]
Good luck
