### ISSUE TITLE
SSO with GitHub

### ISSUE THREAD

**Issue by sveredyuk** [DevChallengeIT/devchallenge-platform#2]

**Comment by PyrinAndrii** [comment]
to implement this should we use smt like https://github.com/workos/workos-ruby or https://github.com/onelogin/ruby-saml?

**Comment by sveredyuk** [comment]
Nope, it's should be simple Login with Google / Github as on pivroak:
<img width="383" alt="Screenshot 2022-05-19 at 16 37 21" src="https://user-images.githubusercontent.com/5221643/169306589-e9d403cd-ef3f-42fd-951b-4efb6084cd97.png">
