### ISSUE TITLE
[Bug] Fix Trix css

### ISSUE THREAD

**Issue by sveredyuk** [DevChallengeIT/devchallenge-platform#51]
<img width="1552" alt="Screenshot 2022-05-12 at 16 56 59" src="https://user-images.githubusercontent.com/5221643/168092199-91be4327-b350-4823-a543-5bb7368d0e1a.png">

**Comment by PyrinAndrii** [comment]
@sveredyuk what do you mean here by `Fix Trix css`? Should we add some styles here? or delete these buttons? others options?

**Comment by sveredyuk** [comment]
@PyrinAndrii idk why but css for trix editor is not working properly
Shold be something like this: https://trix-editor.org/

<img width="822" alt="Screenshot 2022-05-19 at 14 28 18" src="https://user-images.githubusercontent.com/5221643/169283120-3f16cbf2-a4b4-4d26-a79e-f1cb79dcbca9.png">
.
